kind: Service
apiVersion: v1
metadata:
  name: yz-tx-front-service
spec:
  selector:
    app: yz-tx-front
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yz-tx-front
  labels:
    app: yz-tx-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yz-tx-front
  template:
    metadata:
      labels:
        app: yz-tx-front
    spec:
      containers:
      - name: node-yz-tx-front
        image: registry.cn-chengdu.aliyuncs.com/yiezi/yz-tx-front:API_TAG
        ports:
        - containerPort: 8000